
-- Insert 2 Account, the Password is 123456 when you use to sign in. Below is hashed password, only use for saving in database not use for Sign in
INSERT INTO Users (Username, Password)
VALUES ('HoangHuy', 'YGB7qhocFpyoT0Qs/xYQ9Uo0Jsz4f535mI1eUQie2uM='),
		('Elrich', 'YGB7qhocFpyoT0Qs/xYQ9Uo0Jsz4f535mI1eUQie2uM=');

-- Insert some data
INSERT INTO Blogs (Title, Content, UserId)
VALUES	('The Power of Positive Thinking', 'Have you ever noticed how your thoughts can influence your mood and behavior? When we think positively, we tend to feel happier and more motivated to take action. On the other hand, negative thoughts can leave us feeling down and discouraged.<br><br>That''s why it''s so important to cultivate a positive mindset. By focusing on the good in our lives and finding reasons to be grateful, we can train our brains to look for the positive in every situation.<br><br>Of course, this is easier said than done. It takes time and practice to develop a positive outlook on life. But with a little effort, we can all learn to see the world in a more positive light.<br><br>So the next time you catch yourself thinking negative thoughts, try to reframe them in a positive way. Instead of dwelling on what''s going wrong, focus on what''s going right. And remember, a positive attitude can make all the difference in the world.',
		1),

		('The Latest Advancements in Technology', 'Technology is constantly evolving, and it can be difficult to keep up with the latest advancements. From artificial intelligence to blockchain to 5G, there are so many new technologies that are shaping the future.<br><br>One of the most exciting developments is the rise of AI and machine learning. These technologies are being used in everything from self-driving cars to virtual assistants to medical diagnosis. The possibilities are endless, and we are only scratching the surface of what AI can do.<br><br>Blockchain is another technology that is changing the game. Originally developed for Bitcoin, blockchain is now being used in a wide range of industries, from finance to healthcare to supply chain management. Its decentralized nature makes it more secure and transparent than traditional systems.<br><br>And let''s not forget about 5G. This next-generation wireless technology is faster and more reliable than ever before, making it possible to connect more devices and support new applications.<br><br>Overall, these new technologies are transforming the world we live in, and we can expect even more exciting developments in the years to come.',
		1),

		('Top 5 Gadgets and Consumer Electronics You Need to Check Out', 'In today''s fast-paced world, gadgets and consumer electronics have become an integral part of our lives. Here are the top 5 gadgets and consumer electronics you need to check out: <br><br>1. Apple iPhone 13 <br>2. Sony WH-1000XM4 headphones <br>3. Amazon Echo Dot <br>4. Samsung Galaxy Watch 4 <br>5. DJI Mavic Air 2 drone',
		1),

		('Simple Habits for a Healthier Lifestyle',
		'In today''s busy world, it can be easy to neglect our health and wellbeing. However, taking care of ourselves should be a top priority. By adopting a few simple habits, we can improve our overall quality of life and feel better both physically and mentally. Here are some easy habits to help you lead a healthier lifestyle: 1. Stay hydrated: Drink plenty of water throughout the day to keep your body hydrated and functioning properly. 2. Get moving: Incorporate physical activity into your daily routine, even if it''s just a short walk around the block. 3. Eat a balanced diet: Aim to consume a variety of nutrient-dense foods, including fruits, vegetables, whole grains, and lean proteins. 4. Practice self-care: Take time for yourself each day to relax and unwind, whether it''s through meditation, reading, or simply taking a bubble bath. 5. Get enough sleep: Make sure you''re getting enough quality sleep each night to help your body recharge and stay healthy. By making these simple habits a part of your daily routine, you can improve your health and wellbeing in a sustainable way. Remember, taking care of yourself is the first step to living a happy and fulfilling life.',
		1),

		('The Importance of Finding Balance in Your Life',
		'In today''s fast-paced world, it can be easy to get caught up in the hustle and bustle of everyday life. Between work, family, and social obligations, it can feel like there''s never enough time in the day. However, it''s important to remember the value of finding balance in your life. This means taking time to focus on your physical, emotional, and spiritual well-being, and making sure that you''re not neglecting any one area of your life. Whether it''s taking a yoga class, spending time with loved ones, or simply unplugging from technology and enjoying some quiet time alone, finding balance is essential for leading a healthy and fulfilling life. So if you''re feeling overwhelmed or stressed out, take a step back and think about what areas of your life might be out of balance. Then, make a plan to prioritize those areas and find ways to bring more harmony into your daily routine. Remember, life is all about balance, and finding that balance is key to achieving true happiness and fulfillment.',
		1),

		('Tips for Maintaining a Healthy Lifestyle',
		'Maintaining a healthy lifestyle is essential for our overall well-being. It''s not just about eating well and exercising regularly, but also about taking care of our mental and emotional health. Here are some tips for maintaining a healthy lifestyle:<br><br>1. Eat a balanced diet: A balanced diet that includes plenty of fruits, vegetables, lean proteins, and whole grains is important for our health. Avoid processed foods, sugary drinks, and excessive amounts of alcohol.<br><br>2. Exercise regularly: Exercise is important for both our physical and mental health. Aim for at least 30 minutes of moderate exercise most days of the week.<br><br>3. Get enough sleep: Sleep is essential for our physical and mental health. Aim for 7-8 hours of sleep each night.<br><br>4. Manage stress: Stress can have a negative impact on our health. Find healthy ways to manage stress, such as meditation, yoga, or spending time outdoors.<br><br>5. Stay connected: Social connections are important for our mental health. Stay connected with friends and family, and find ways to meet new people.<br><br>By incorporating these tips into our daily lives, we can maintain a healthy lifestyle and improve our overall well-being.',
		1),

		('The Importance of Rest Days in Your Fitness Routine',
		'When it comes to achieving your fitness goals, it can be tempting to push yourself to the limit every day. However, rest days are just as important as your workout days.<br><br>Rest days give your body time to recover and repair, which is crucial for building muscle and preventing injury. They also help prevent burnout and fatigue, which can set you back in your fitness journey.<br><br>But what should you do on your rest days? The key is to stay active without pushing yourself too hard. This could mean going for a light walk, doing some gentle yoga, or simply stretching.<br><br>So don''t underestimate the importance of rest days in your fitness routine. Your body will thank you for the extra recovery time, and you''ll see better results in the long run.',
		2),

		('The Benefits of Spending Time Outdoors',
		'Spending time outdoors can have numerous benefits for both our physical and mental health. Whether it''s hiking, camping, or just taking a walk in the park, getting outside and enjoying nature can help us feel more relaxed and rejuvenated. One of the biggest benefits of outdoor recreation is the physical activity it provides. Activities like hiking, kayaking, and rock climbing can help us stay fit and healthy. And because they''re fun and engaging, we''re more likely to stick with them long-term. Being outside in nature also has mental health benefits. Studies have shown that spending time in nature can reduce stress, anxiety, and depression. It can also improve our mood and boost our creativity. And let''s not forget about the social benefits of outdoor recreation. Participating in group activities like camping trips and sports leagues can help us connect with others who share our interests and values. So the next time you''re feeling stressed or overwhelmed, consider taking a break and heading outside for some fresh air and exercise. Your body and mind will thank you.',
		2),

		('The Joys of Solo Travel',
		'Traveling alone can be intimidating, but it can also be an incredibly rewarding experience. When you''re on your own, you have the freedom to go wherever you want, whenever you want. You don''t have to worry about coordinating with anyone else or compromising on what to do.<br><br>Solo travel can also help you become more independent and self-reliant. You learn to navigate unfamiliar places, communicate with people from different cultures, and problem-solve on your own.<br><br>Of course, there are also downsides to solo travel. You might feel lonely at times, and there''s always a risk of running into trouble without anyone to help you. But with common sense and some basic precautions, the rewards far outweigh the risks.<br><br>So if you''ve never traveled alone before, why not give it a try? You might be surprised at how much you enjoy it.',
		2),

		('The Importance of Protecting the Environment',
		'The environment is a precious resource that we must work to protect. From clean air and water to diverse ecosystems, our planet provides us with everything we need to survive and thrive.<br><br>Unfortunately, human activities like deforestation, pollution, and overfishing are putting our environment at risk. Climate change is also a major threat, with rising temperatures and sea levels causing serious damage to our planet.<br><br>That''s why it''s so important to take action to protect the environment. We can all do our part by reducing our carbon footprint, conserving water, and supporting sustainable practices.<br><br>We can also support policies and initiatives that promote environmental protection, like investing in renewable energy and preserving natural habitats.<br><br>Remember, we only have one planet, and it''s up to us to ensure that it remains a healthy and habitable place for generations to come.',
		2),

		('Home Decorating Ideas for Small Spaces',
		'Living in a small apartment or house can be challenging, especially when it comes to decorating. But just because you have limited space doesn''t mean you can''t create a beautiful and functional home. Here are some home decorating ideas for small spaces:<br><br>1. Use mirrors to create the illusion of more space. Hang a large mirror on the wall or lean it against a wall to reflect light and make the room appear larger.<br><br>2. Choose furniture that can serve multiple purposes. For example, a sofa bed can be used for seating during the day and as a bed at night.<br><br>3. Invest in storage solutions to keep clutter at bay. Use baskets, shelves, and cabinets to store items and keep them out of sight.<br><br>4. Use color to create a cohesive look. Stick to a color scheme and use it throughout the room to tie everything together.<br><br>5. Choose furniture and decor that is proportionate to the space. Avoid oversized pieces that will overwhelm the room.<br><br>By following these tips, you can make the most of your small space and create a home that is both stylish and functional.',
		2),

		('A Guide to Men''s Fashion',
		'Fashion isn''t just for women anymore. Men''s fashion has come a long way in recent years, and now there are more options than ever for men who want to look stylish and put-together. From classic suits to casual streetwear, there are plenty of ways to express your personal style and make a statement with your fashion choices.

One of the keys to dressing well as a man is to focus on fit. Clothes that fit well will always look better than clothes that don''t, regardless of how much they cost or how fashionable they are. It''s worth investing in a few high-quality pieces that fit you perfectly, rather than a lot of cheaper clothes that don''t.

Another important aspect of men''s fashion is to pay attention to the details. Accessories like watches, belts, and shoes can make a big difference in the overall look of an outfit. Don''t be afraid to experiment with different styles and colors to find what works for you.

Overall, men''s fashion is all about expressing yourself and feeling confident in your own skin. With a little bit of effort and attention to detail, anyone can look great and feel great in what they wear.',
		2);

